- name: 'Some OAuth Provider'
  redirect_uri: 'http://localhost:4567/oauth_cb?provider=BFH'
  client_id: 'client_id'
  client_secret: 'secret'
  scopes:
    - 'email'
    - 'profile'
    - 'openid'
  external_userid: 'nickname'
  authorization_endpoint: 'https://authorize'
  token_endpoint: 'https://token'
  userinfo_endpoint: 'https://userinfo'
  response_type: 'code'
