profile:
  - name
  - family_name
  - given_name
  - middle_name
  - nickname
  - preferred_username
  - profile
  - picture
  - website
  - gender
  - birthdate
  - zoneinfo
  - locale
  - updated_at
email:
  - email
  - email_verified
address:
  - address
phone:
  - phone_number
  - phone_number_verified
omejdn:api: 
  - omejdn:api
omejdn:admin:
  - omejdn:admin
openid:
  - openid
idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
  - securityProfile
  - referringConnector
  - "@type"
  - "@context"
  - transportCertsSha256
