---
plugins:
  user_db:
    yaml:
      location: config/users.yml
  claim_mapper:
    attribute:
      skip_access_token: false
      skip_id_token: true
  api:
    admin_v1: 
    user_selfservice_v1:
      allow_deletion: false
      allow_password_change: true
      editable_attributes: []
user_backend_default: yaml
environment: development